# Generated by Django 4.1.7 on 2023-03-29 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0003_alter_task_assignees_alter_task_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, related_name="workers", to="manager.task"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(
                related_name="assigned_task", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
