# Generated by Django 4.1.7 on 2023-03-30 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0004_worker_tasks_alter_task_assignees"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["deadline"],
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
            },
        ),
        migrations.RemoveField(
            model_name="worker",
            name="tasks",
        ),
        migrations.AlterField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(
                related_name="tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
