# Generated by Django 4.1.7 on 2023-03-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0005_alter_task_options_remove_worker_tasks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(),
        ),
    ]
